language: python
python: "2.7"

addons:
    apt:
        packages:
            - sshpass

script:
    - mkdir build
    - cp -R ./!(build) build
    - tar -czf package.tgz build
    - rm -rf build

before_install: npm install -g grunt-cli

install:
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o stricthostkeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh $DEPLOY_SITE


