language: python
python: "2.7"

branches:
  only:
    - master
    - develop

addons:
    apt:
        packages:
            - sshpass

script: npm install -g grunt-cli

before_install: 
    - mkdir build
    - cp -R ./!(build) build
    - tar -czf package.tgz build
    - rm -rf build

install:
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o stricthostkeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_PATH && tar -xzf package.tgz && rm deploy.sh && cp build/deploy.sh deploy.sh && rm -rf build"
    - sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh $DEPLOY_SITE


