language: python
addons:
    apt:
        packages:
            - sshpass

after_success:
    - mkdir /tmp/build
    - mv * /tmp/build
    - tar -czf package.tgz /tmp/build
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh